### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by ghost** [NITR098/AttSwinUNet#2]
Hi, I'm trying to run your model.

At "Prepare data and pretrained model" part, in the 3rd point I need the "Train_Skin_Lesion_Segmentation.py" file. I don't find it in the repository. 
Also, I'm having issues with this instruction: from networks.attention_swin_unet import SwinAttentionUnet as ViT_seg
I have downloaded all the requirements in the "requirements.txt", as you indicate, and I don't know how to fix this.

Thanks for your help : )

**Comment by maralzar** [comment]
you do not need this file I remove from read me please just run train.py after preparing dataset.
