### ISSUE TITLE
from utils import load_pretrain

### ISSUE THREAD

**Issue by Seaz9** [NITR098/AttSwinUNet#4]
I can‘t find the utils files，when I run the rode，it tell me it can't find the load_pretrain,can you help me?

**Comment by TWENTY-FOU** [comment]
同问
解决了可以艾特一下我嘛？

**Comment by TWENTY-FOU** [comment]
邮箱1002367554@qq.com

**Comment by Kahsolt** [comment]
That `load_pretrain` seems redundant and can be just safely removed, see line 104~106 for the real load of pretrained weights:

```
if int(config['pretrained']):
    Net.load_state_dict(torch.load(config['saved_model'], map_location='cpu')['model_weights'])
    best_val_loss = torch.load(config['saved_model'], map_location='cpu')['val_loss']
```

And also, when it comes to error missing `xcit_tiny_12_p16`, just comment that two lines, they are NOT EVEN USED. 
And then, when `trainer is a module and cannot be called`, modify its import clause `from trainer import trainer`.
And finally, I got `AssertionError: Input image size (256*256) doesn't match model (224*224).` only to find that the pretrained model is sized 244 and cannot even apply on ANY DATASET PRESETS sized in 256 as `README.md` declares!!!!!

After all, I DO NOT really know why this repo is soooo broken...
Is this really an official implementation for a published or ready-to-publish work??
It upsets me a bit :(
